--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/22/2015 9:27:55 PM
-- Server version: 5.6.24
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE fariasc2013;

--
-- Definition for table activities
--
DROP TABLE IF EXISTS activities;
CREATE TABLE activities (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  description LONGTEXT DEFAULT NULL,
  user LONGTEXT DEFAULT NULL,
  uploadDate DATETIME NOT NULL,
  photo VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 20
AVG_ROW_LENGTH = 2048
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table events
--
DROP TABLE IF EXISTS events;
CREATE TABLE events (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user INT(11) NOT NULL,
  eventlist VARCHAR(16) DEFAULT NULL,
  photoname VARCHAR(255) DEFAULT NULL,
  description LONGTEXT DEFAULT NULL,
  uploaddate DATE DEFAULT NULL,
  ename VARCHAR(255) DEFAULT NULL,
  act_link INT(11) DEFAULT NULL,
  rsvp LONGTEXT DEFAULT NULL,
  loct LONGTEXT DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 41
AVG_ROW_LENGTH = 564
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table notifications
--
DROP TABLE IF EXISTS notifications;
CREATE TABLE notifications (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(16) NOT NULL,
  initiator VARCHAR(16) NOT NULL,
  app VARCHAR(255) NOT NULL,
  note VARCHAR(255) NOT NULL,
  did_read ENUM('0','1') NOT NULL DEFAULT '0',
  date_time DATETIME NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table useroptions
--
DROP TABLE IF EXISTS useroptions;
CREATE TABLE useroptions (
  id INT(11) NOT NULL,
  username VARCHAR(16) NOT NULL,
  background VARCHAR(255) NOT NULL,
  question VARCHAR(255) DEFAULT NULL,
  answer VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX username (username)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table users2
--
DROP TABLE IF EXISTS users2;
CREATE TABLE users2 (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(16) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  signup DATETIME NOT NULL,
  notescheck DATETIME NOT NULL,
  activated ENUM('0','1') NOT NULL DEFAULT '0',
  actlist LONGTEXT DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX username (username, email)
)
ENGINE = INNODB
AUTO_INCREMENT = 18
AVG_ROW_LENGTH = 2730
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table activities
--
INSERT INTO activities VALUES
(12, 'Soccer', '', NULL, '0000-00-00 00:00:00', NULL),
(13, 'Rowing', NULL, NULL, '0000-00-00 00:00:00', NULL),
(14, 'Archery', NULL, NULL, '0000-00-00 00:00:00', NULL),
(15, 'Volleyball', NULL, NULL, '0000-00-00 00:00:00', 'banner.png'),
(16, 'Baseball', NULL, NULL, '0000-00-00 00:00:00', NULL),
(17, 'Football', NULL, NULL, '0000-00-00 00:00:00', NULL),
(18, 'Running', NULL, NULL, '0000-00-00 00:00:00', NULL),
(19, 'Judo', NULL, NULL, '0000-00-00 00:00:00', NULL);

-- 
-- Dumping data for table events
--
INSERT INTO events VALUES
(12, 12, NULL, NULL, 'This is a long description', NULL, 'Test1', 19, '13 12', NULL),
(13, 12, NULL, NULL, 'New Event', NULL, 'Test 2', 19, '12', NULL),
(14, 12, NULL, NULL, 'This is a test', '2015-07-24', 'New Soccer Event', 12, '12', '33428'),
(15, 12, NULL, NULL, 'aaaa', '2015-07-24', 'Test', 19, NULL, '3333'),
(16, 12, NULL, NULL, 'aa', '2015-07-24', 'Test 3', 19, NULL, '33'),
(17, 12, NULL, NULL, 'aa', '2015-07-24', 'Test 3', 19, '124 12 164', '33'),
(18, 12, NULL, NULL, 'aaa', '2015-07-18', 'testsw', 19, NULL, '333'),
(19, 12, NULL, NULL, 'aaa', '2015-07-18', 'testsw', 19, NULL, '333'),
(20, 12, NULL, NULL, '11', '2015-07-18', 'mmmm', 19, NULL, '111'),
(21, 12, NULL, NULL, '11', '2015-07-18', 'mmmm', 19, NULL, '111'),
(22, 12, NULL, NULL, 'afafa', '2015-07-14', 'afafafaf', 19, NULL, 'afafa'),
(23, 12, NULL, NULL, '5216916', '2015-08-28', 'This is a long event', 19, NULL, '252525'),
(24, 12, NULL, NULL, 'aa', '2015-07-21', 'this is a testtsstst', 19, NULL, 'aa'),
(25, 12, NULL, NULL, 'aaaaa', '2014-12-30', 'This is a newwww test', 19, NULL, 'aaaa'),
(26, 16, NULL, NULL, 'aa', '2015-07-29', 'Test', 15, NULL, '3333'),
(27, 16, NULL, NULL, 'aa', '2015-07-29', 'Test', 15, NULL, '3333'),
(28, 16, NULL, NULL, 'aaa', '2015-07-21', 'testt', 15, NULL, 'aaaaaa'),
(29, 16, NULL, NULL, '5656565656565656', '2015-07-31', 'This is a new test', 15, NULL, '565656565'),
(30, 16, NULL, NULL, '5656565656565656', '2015-07-31', 'This is a new test', 15, NULL, '565656565'),
(31, 16, NULL, NULL, '5656565656565656', '2015-07-31', 'This is a new test', 15, NULL, '565656565'),
(32, 16, NULL, NULL, '3333', '2014-12-30', 'test', 15, '16 12', '333'),
(33, 16, NULL, NULL, 'adsadfsa', '2018-12-30', 'tests', 15, NULL, '33254'),
(34, 16, NULL, NULL, '1313', '2015-12-31', 'tests', 15, NULL, '1331'),
(35, 16, NULL, NULL, '222', '2017-01-31', 'test', 15, NULL, '21222'),
(36, 16, NULL, NULL, '121312313', '2017-01-02', 'test', 15, NULL, '1321212'),
(37, 16, NULL, NULL, '121321313', '2016-01-02', 'the real test', 15, NULL, '121212'),
(38, 16, NULL, NULL, '121321313', '2016-01-02', 'the real test', 15, NULL, '121212'),
(39, 16, NULL, 'Cnh2.png', '121321313', '2016-01-02', 'the real test', 15, NULL, '121212'),
(40, 16, NULL, NULL, '12121', '2014-12-30', 'this is a new testt', 19, NULL, '11212');

-- 
-- Dumping data for table notifications
--

-- Table fariasc2013.notifications does not contain any data (it is empty)

-- 
-- Dumping data for table useroptions
--

-- Table fariasc2013.useroptions does not contain any data (it is empty)

-- 
-- Dumping data for table users2
--
INSERT INTO users2 VALUES
(12, 'andrews', 'andrews@gmail.com', 'aa', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0', '12,13,15,19'),
(13, 'test', 'test@gmail.com', 'test', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0', NULL),
(14, 'andrewsa', 'andrewsa@gmail.com', 'aaaa', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0', NULL),
(15, 'aleao', 'andrew@g.com', '12', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0', NULL),
(16, 'ahleao', 'a@a.com', 'aa', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0', '15,12,19,14'),
(17, 'a', 'aa@a.com', 'a', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0', NULL);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;